export const DRAGON_SET_VALUE = 'DRAGON/SET_VALUE';
export const DRAGON_ADD_DRAGON = 'DRAGON/ADD_DRAGON';

export const KNIGHT_SET_VALUE = 'KNIGHT/SET_VALUE';
export const KNIGHT_ADD_KNIGHT = 'KNIGHT/ADD_KNIGHT';